"""Per-clip social metadata: YouTube/TikTok/Instagram title, description, tags
and hashtags, generated by the local LLM against a user-supplied campaign brief.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence

from ..llm.base import LLMBackend, LLMError
from ..llm.json_repair import parse_json
from ..llm.prompts import METADATA_SCHEMA, METADATA_SYSTEM, metadata_prompt
from .exporters import safe_stem

log = logging.getLogger("clipfinder.metadata")


def _str_list(value: Any) -> List[str]:
    if not isinstance(value, list):
        return []
    return [str(v).strip() for v in value if str(v).strip()]


def generate_clip_metadata(
    backend: LLMBackend,
    clip: Dict[str, Any],
    language: str,
    campaign_rules: str = "",
    on_log: Optional[Callable[[str], None]] = None,
) -> Optional[Dict[str, Any]]:
    """One LLM call -> publish-ready metadata for one clip, or None on failure."""
    title = str(clip.get("title", "") or "")
    transcript = " ".join(str(clip.get("transcript", "")).split())
    prompt = metadata_prompt(
        title, transcript, str(clip.get("type", "other")),
        float(clip.get("duration", 0) or 0), language, campaign_rules,
        hook_line=str(clip.get("hook_line", "") or ""),
        virality=float(clip.get("virality", 0) or 0),
    )
    try:
        raw = backend.complete(METADATA_SYSTEM, prompt, METADATA_SCHEMA, on_log=on_log)
    except LLMError as exc:
        if on_log:
            on_log(f"Metadata for clip #{clip.get('rank')} failed: {exc}")
        return None

    data = parse_json(raw)
    if isinstance(data, list) and data:
        data = data[0]
    if not isinstance(data, dict):
        return None

    return {
        "youtube_title": str(data.get("youtube_title", "") or title).strip()[:100],
        "youtube_description": str(data.get("youtube_description", "") or "").strip(),
        "youtube_tags": _str_list(data.get("youtube_tags")),
        "tiktok_description": str(data.get("tiktok_description", "") or "").strip(),
        "tiktok_hashtags": _str_list(data.get("tiktok_hashtags")),
        "instagram_description": str(data.get("instagram_description", "") or "").strip(),
        "instagram_hashtags": _str_list(data.get("instagram_hashtags")),
        "mentions": _str_list(data.get("mentions")),
    }


def format_metadata_text(meta: Dict[str, Any], clip: Dict[str, Any]) -> str:
    lines: List[str] = [
        f"CLIP #{clip.get('rank')} — {clip.get('title', '')}",
        f"{clip.get('start_tc', '')} -> {clip.get('end_tc', '')}  "
        f"({round(float(clip.get('duration', 0) or 0))}s)",
        "=" * 66,
        "",
        "YOUTUBE",
        "-" * 66,
        f"Title: {meta.get('youtube_title', '')}",
        "Description:",
        meta.get("youtube_description", ""),
        "Tags: " + ", ".join(meta.get("youtube_tags", [])),
        "",
        "TIKTOK",
        "-" * 66,
        "Description:",
        meta.get("tiktok_description", ""),
        "Hashtags: " + " ".join(meta.get("tiktok_hashtags", [])),
        "",
        "INSTAGRAM",
        "-" * 66,
        "Description:",
        meta.get("instagram_description", ""),
        "Hashtags: " + " ".join(meta.get("instagram_hashtags", [])),
        "",
    ]
    if meta.get("mentions"):
        lines += ["MENTIONS (required by the campaign brief)", "-" * 66,
                  ", ".join(meta["mentions"]), ""]
    lines += [
        "ALGORITHM TIPS", "-" * 66,
        "- Post the hook frame first - no logo/intro before the payoff starts.",
        "- Reply to the first comments within the first hour; early replies signal",
        "  the algorithm to keep pushing the clip.",
        "- TikTok/Reels: completion rate and rewatches matter more than likes -",
        "  this clip's boundaries were already trimmed to open and close tight.",
        "- Post consistently rather than chasing perfect timing; the account's",
        "  posting cadence matters more than the hour of the day.",
        "",
    ]
    return "\n".join(lines)


def write_metadata_for_clips(
    backend: LLMBackend,
    clips: Sequence[Dict[str, Any]],
    folder: Path,
    language: str = "en",
    campaign_rules: str = "",
    on_progress: Optional[Callable[[int, int, str], None]] = None,
    on_log: Optional[Callable[[str], None]] = None,
) -> Dict[str, Any]:
    """Write one `<clip>_metadata.txt` per clip into `folder`. Best-effort: a
    clip whose LLM call fails is skipped, not fatal to the whole export.

    Returns {"written": [paths], "failed": [ranks]} so the caller can tell the
    user precisely what happened instead of a silent miss.
    """
    folder.mkdir(parents=True, exist_ok=True)
    written: List[str] = []
    failed: List[Any] = []
    total = len(clips)
    for n, clip in enumerate(clips, start=1):
        if on_progress:
            on_progress(n, total, f"Writing metadata for clip #{clip.get('rank')}")
        meta = generate_clip_metadata(backend, clip, language, campaign_rules, on_log=on_log)
        if not meta:
            failed.append(clip.get("rank", n))
            continue
        rank = clip.get("rank", n)
        title = safe_stem(str(clip.get("title", "")).strip(), 40) or str(clip.get("type", "clip"))
        try:
            prefix = f"clip_{int(rank):02d}"
        except (TypeError, ValueError):
            prefix = safe_stem(str(rank), 30)
        path = folder / f"{prefix}_{title}_metadata.txt"
        path.write_text(format_metadata_text(meta, clip), encoding="utf-8")
        written.append(str(path))
    return {"written": written, "failed": failed}
